jobs:
  - name: u14all-testing
    type: runSh
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/u14all"
              imageTag: master
          script:
         
            - elasticsearch --version
            - memcached --version
