jobs:
  - name: u14all-testing
    type: runSh
    steps:
      - IN: cli-test
      - TASK:
          runtime:
            options:
              imageName: "drydock/u14all"
              imageTag: master
          script:
         
            - elasticsearch --version
            - memcached --version
            - cassandra -v
            - riak version
            - service couchdb start
            - sleep 5
            - curl http://127.0.0.1:5984  
            - psql --version
            - java -jar /usr/local/selenium/selenium-server-standalone-3.11.0.jar --version
            - sqlite3 --version
            - mysql --version
            - mongod --version
            - /var/lib/neo4j/bin/neo4j version
            - dpkg -s rabbitmq-server | grep Version
            - redis-server --version
