jobs:
  - name: u14all-testing
    type: runSh
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/u14all"
              imageTag: master
          script:
         
            - elasticsearch --version
            - memcached --version
            - cassandra -v
            - riak version
            - service couchdb start
            - curl http://127.0.0.1:5984  
